apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mattel-routing-app
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Container dependencies: web-app starts after fastapi
        run.googleapis.com/container-dependencies: "{web-app: [fastapi]}"
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Timeout for requests
      timeoutSeconds: 300
      containers:
      # Web App - Main application container (React frontend)
      - image: us-central1-docker.pkg.dev/casual-athenas-25xa7/mattel-routing/web-app@sha256:97ed2bf0539230bbc0f53ff7db99dd006b99e73b8a5e5e757ceacbcae27598d1
        name: web-app
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_API_BASE_URL
          value: "http://127.0.0.1:8000"
      
      # FastAPI Backend - API service container
      - image: us-central1-docker.pkg.dev/casual-athenas-25xa7/mattel-routing/fastapi-app@sha256:2d02bb8958b611c215a7ab18fc2c147873a7498b745f297359ade61301ede5a8
        name: fastapi
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12 