apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mattel-routing-app
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Container dependencies: web-app starts after fastapi
        run.googleapis.com/container-dependencies: "{web-app: [fastapi]}"
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Timeout for requests
      timeoutSeconds: 300
      containers:
      # Web App - Main application container (React frontend)
      - image: us-central1-docker.pkg.dev/PROJECT_ID/mattel-routing/web-app:latest
        name: web-app
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_API_BASE_URL
          value: "http://127.0.0.1:8000"
      
      # FastAPI Backend - API service container
      - image: us-central1-docker.pkg.dev/PROJECT_ID/mattel-routing/fastapi-app:latest
        name: fastapi
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12
        volumeMounts:
        - name: app-data
          readOnly: true
          mountPath: /app/data
      
      volumes:
      # Application data
      - name: app-data
        emptyDir: {} 