apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mattel-routing-app
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Container dependencies: nginx starts after fastapi
        run.googleapis.com/container-dependencies: "{nginx: [fastapi]}"
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Timeout for requests
      timeoutSeconds: 300
      containers:
      # Nginx Sidecar - Acts as reverse proxy and static file server
      - image: us-central1-docker.pkg.dev/PROJECT_ID/mattel-routing/nginx-proxy:latest
        name: nginx
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: nginx-config
          readOnly: true
          mountPath: /etc/nginx/conf.d/
        - name: static-files
          readOnly: true
          mountPath: /usr/share/nginx/html
        env:
        - name: FASTAPI_HOST
          value: "127.0.0.1"
        - name: FASTAPI_PORT
          value: "8000"
      
      # FastAPI Backend - Main application container
      - image: us-central1-docker.pkg.dev/PROJECT_ID/mattel-routing/fastapi-app:latest
        name: fastapi
        env:
        - name: PORT
          value: "8000"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: app-data
          readOnly: true
          mountPath: /app/data
      
      volumes:
      # Nginx configuration from Secret Manager
      - name: nginx-config
        secret:
          secretName: nginx-sidecar-config
          items:
          - key: latest
            path: default.conf
      
      # Static files volume (shared between containers)
      - name: static-files
        emptyDir: {}
      
      # Application data
      - name: app-data
        emptyDir: {} 